creato il file due array
Lomba0job/Esercitazione_c pull request #4
Opened 2024-03-05 18:03 UTC by RED-ITA

2024-03-05 18:12 UTC, Lomba0job requested changes
Aggiungere i commenti linea per linea 
Aggiungere l output del programma

2024-03-06 13:50 UTC, Lomba0job commented on esercizio_doppio_array.c
> +    int v[N], v2[N], i2=0;
Commenta liena per liena.. esempio, qui //allocazione di due array di dimensione fissa N e una variabile int a vlaore iniziale 0
```suggestion
    int v[N], v2[N], i2=0;
```

2024-03-06 13:51 UTC, Lomba0job commented on esercizio_doppio_array.c
> +
Copia ed incolla quella che visualizzi Sule terminale quando lanci l'esequzione

2024-03-06 17:15 UTC, RED-ITA reviewed
terminato

2024-03-06 17:16 UTC, Lomba0job approved these changes

2024-03-06 17:17 UTC, Lomba0job approved these changes

2024-03-06 17:17 UTC, merged